
name: 'jaffle_shop'
config-version: 2
version: '0.1'
profile: 'jaffle_shop'
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"
    - "dbt_packages"

vars:
  asana_source:
    asana_schema: fivetran_asana 


seeds:
  +quote_columns: false
  
models:
  transient: true
  jaffle_shop:
      sources:
        +materialization: views
        tiktok:
          +schema: sources_tiktok